use_frameworks!

platform :ios, '13.0'

target 'TKBadgeView_Example' do
  pod 'TKBadgeView', :path => '../'

  target 'TKBadgeView_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
